language: python
cache: pip
python: 3.7
services:
  - docker
before_install:
  - docker pull bl4ck5un/unoconv
install:
  - 'pip install -r requirements.txt'
  # `awscli` is required for invalidation of CloudFront distributions.
  - 'pip install awscli'
script:
  - 'make -C content/press -f Makefile.travis'
  - 'python main.py --deploy'
after_success:
  # compress the html and images using gzip
  - 'chmod u+x compress.sh && ./compress.sh'
deploy:
  -
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: www.initc3.org
    region: us-east-1
    skip_cleanup: true
    default_text_charset: utf-8
    # Set the Cache-Control header.
    cache_control: max-age=43200
    local-dir: output
    detect_encoding: true
    on:
      branch: master
  -
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: staging.initc3.org
    region: us-east-1
    skip_cleanup: true
    default_text_charset: utf-8
    cache_control: max-age=43200
    local-dir: output
    detect_encoding: true
    on:
      branch: staging
after_deploy:
  # allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  email:
    recipients:
      - admin@initc3.org
    on_failure: always
